### ISSUE TITLE
stap -g get_memcg_count.stp 报错

### ISSUE THREAD

**Issue by cncal** [kongfei605/cgroup_leak_fix#8]
在执行 `stap -g get_memcg_count.stp` 时程序报错：

```shell
root@host99:~# stap -g get_memcg_count.stp 
/tmp/stapVSuxcK/stap_879c7e3559ae3aed739a9897f8b06460_1909_src.c: In function ‘get_memcg_count’:
/tmp/stapVSuxcK/stap_879c7e3559ae3aed739a9897f8b06460_1909_src.c:50:31: error: implicit declaration of function ‘css_lookup’ [-Werror=implicit-function-declaration]
                         tmp = css_lookup(&mem_cgroup_subsys, i);
                               ^
/tmp/stapVSuxcK/stap_879c7e3559ae3aed739a9897f8b06460_1909_src.c:50:43: error: ‘mem_cgroup_subsys’ undeclared (first use in this function)
                         tmp = css_lookup(&mem_cgroup_subsys, i);
                                           ^
/tmp/stapVSuxcK/stap_879c7e3559ae3aed739a9897f8b06460_1909_src.c:50:43: note: each undeclared identifier is reported only once for each function it appears in
/tmp/stapVSuxcK/stap_879c7e3559ae3aed739a9897f8b06460_1909_src.c: At top level:
cc1: error: unrecognized command line option ‘-Wno-misleading-indentation’ [-Werror]
cc1: all warnings being treated as errors
scripts/Makefile.build:277: recipe for target '/tmp/stapVSuxcK/stap_879c7e3559ae3aed739a9897f8b06460_1909_src.o' failed
make[1]: *** [/tmp/stapVSuxcK/stap_879c7e3559ae3aed739a9897f8b06460_1909_src.o] Error 1
Makefile:1494: recipe for target '_module_/tmp/stapVSuxcK' failed
make: *** [_module_/tmp/stapVSuxcK] Error 2
WARNING: kbuild exited with status: 2
Pass 4: compilation failed.  [man error::pass4]
Tip: /usr/share/doc/systemtap/README.Debian should help you get started.

```

**Comment by kongfei605** [comment]
> 在执行 `stap -g get_memcg_count.stp` 时程序报错：
> 
> ```shell
> root@host99:~# stap -g get_memcg_count.stp 
> /tmp/stapVSuxcK/stap_879c7e3559ae3aed739a9897f8b06460_1909_src.c: In function ‘get_memcg_count’:
> /tmp/stapVSuxcK/stap_879c7e3559ae3aed739a9897f8b06460_1909_src.c:50:31: error: implicit declaration of function ‘css_lookup’ [-Werror=implicit-function-declaration]
>                          tmp = css_lookup(&mem_cgroup_subsys, i);
>                                ^
> /tmp/stapVSuxcK/stap_879c7e3559ae3aed739a9897f8b06460_1909_src.c:50:43: error: ‘mem_cgroup_subsys’ undeclared (first use in this function)
>                          tmp = css_lookup(&mem_cgroup_subsys, i);
>                                            ^
> /tmp/stapVSuxcK/stap_879c7e3559ae3aed739a9897f8b06460_1909_src.c:50:43: note: each undeclared identifier is reported only once for each function it appears in
> /tmp/stapVSuxcK/stap_879c7e3559ae3aed739a9897f8b06460_1909_src.c: At top level:
> cc1: error: unrecognized command line option ‘-Wno-misleading-indentation’ [-Werror]
> cc1: all warnings being treated as errors
> scripts/Makefile.build:277: recipe for target '/tmp/stapVSuxcK/stap_879c7e3559ae3aed739a9897f8b06460_1909_src.o' failed
> make[1]: *** [/tmp/stapVSuxcK/stap_879c7e3559ae3aed739a9897f8b06460_1909_src.o] Error 1
> Makefile:1494: recipe for target '_module_/tmp/stapVSuxcK' failed
> make: *** [_module_/tmp/stapVSuxcK] Error 2
> WARNING: kbuild exited with status: 2
> Pass 4: compilation failed.  [man error::pass4]
> Tip: /usr/share/doc/systemtap/README.Debian should help you get started.
> ```

这个脚本是查看cgroup使用程度的。 不是前置依赖，如果想研究下这个脚本，可以先看下include的头文件是否存在，里面是否有css_lookup函数和mem_cgroup_subsys的定义
